name: editor
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  chopper: ^7.4.0
  envied: ^0.5.3
  equatable: ^2.0.5
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.0.1
  http: ^1.2.1
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  video_player: ^2.8.2

dev_dependencies:
  build_runner: ^2.4.8
  chopper_generator: ^7.4.0
  envied_generator: ^0.5.3
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  swagger_dart_code_generator: ^2.15.2

flutter:
  uses-material-design: true
  assets:
    - .env
