name: Build and Release Codec

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Build codec
        run: |
          go build -o ./output/codec/codec_service ./codec/codec.go

      - name: Upload codec artifact
        uses: actions/upload-artifact@v3
        with:
          name: codec_service
          path: ./output/codec/codec_service

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download codec artifact
        uses: actions/download-artifact@v3
        with:
          name: codec_service
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/codec_service
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
