name: Build and Release Golang Microservices

on:
  push:
    tags:
      - "v*" # Trigger on version tags, e.g., v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [codec, ai_assistant, auditor, server]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20 # Adjust Go version as needed

      - name: Build {{ matrix.service }}
        run: |
          cd {{ matrix.service }}
          GOOS=linux GOARCH=amd64 go build -o ../{{ matrix.service }}-linux-amd64

      - name: Upload {{ matrix.service }} binary
        uses: actions/upload-artifact@v3
        with:
          name: "{{ matrix.service }}-linux-binary"
          path: ../{{ matrix.service }}-linux-amd64

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
